### ISSUE TITLE
Demo examples are not working

### ISSUE THREAD

**Issue by achtan** [kadirahq/react-komposer#1]
See this in live: https://jsfiddle.net/07pzx7d7/1/
See this in live: https://jsbin.com/nohuqa/edit?js,output
Check here to it in action: https://goo.gl/K1LhYk/
Try this live: https://jsbin.com/bofaxi/edit?js,output

I am getting error `"ReferenceError: ReactDataBinder is not defined at xazuzo.js:51:13"`

**Comment by arunoda** [comment]
Yeah! That's because, I changes the name.

Use `ReactKomposer.compose` instead of `ReactDataBinder.bindData`. I'll update the samples.
Check the README in few hours.

**Comment by arunoda** [comment]
Check now. Now they are working.
Actually, I've moved demos to JSFiddle.
