### ISSUE TITLE
Should mobx be moved from devDependencies to dependencies in package.json?

### ISSUE THREAD

**Issue by mkdbns** [kadirahq/react-komposer#103]
As of the last release, we are seeing the following error in the browser console for our application:

`Uncaught Error: Cannot find module 'mobx'`

Coming from:

`node_modules.react-komposer.dist.composers.with_mobx.js`

Adding mobx to our dependencies seems to resolve the issue. Seems like mobx should be moved from devDependencies to dependencies in your package.json?

**Comment by arunoda** [comment]
Yes it is. 
I am working on it.

**Comment by arunoda** [comment]
This should be fixed with the latest release. Update the package.

**Comment by SachaG** [comment]
Why does Komposer need to depend on mobx? I thought it was supposed to work with Redux, Meteor, etc. independently ?
