### ISSUE TITLE
Default loading component causes null pointer with React DND

### ISSUE THREAD

**Issue by mbabauer** [kadirahq/react-komposer#105]
I am trying to setup a draggable component using [React DND](https://github.com/gaearon/react-dnd), but I am running into an issue.  I opened an [issue over there](https://github.com/gaearon/react-dnd/issues/468), but after digging deep into the stacktrace, it looks like the issue might be in react-komposer.

Details in in the other issue, but what I found is that the `DefaultLoadingComponent` created on line 76 in browser.js creates the component with a null parent.  When React DND runs, it calls React's `DOMLazyTree.replaceChildWithTree()` (line 68 of DOMLazyTree.js), but since the parent is null, a NPE occurs on line 69.

Is it possible to replace the default loading component?  If not, is there a reason why the parent seems to be null?

**Comment by arunoda** [comment]
There's way to change the default loading component. See docs. We'll have much better solution with 2.x - https://github.com/kadirahq/react-komposer/issues/123
