### ISSUE TITLE
Way to show loading component again

### ISSUE THREAD

**Issue by Narzerus** [kadirahq/react-komposer#118]
After `onData` is called with data, the loading componen is (of course) not rendered anymore.

Is there a way to force that component to show again? I'm building a component which specifically requires to show the `loading...` component again after props change.

**Comment by Narzerus** [comment]
Well, apparently passing `null` as `onData`'s second argument causes the `loading...` component to show again

**Comment by thomasKn** [comment]
Same problem here, I want to show the loading component again:

```
const onPropsChange = (props, onData) => {
  Meteor.call('ordersByDateRange', props.minDate, props.maxDate, props.value, function (error, result) {
    const data = result;
    onData(null, { data });
  });
};

export default composeWithTracker(onPropsChange)(GetOrders);
```

I tried to pass `null` as `onData`'s second argument but no success:

```
const onPropsChange = (props, onData) => {
  Meteor.call('ordersByDateRange', props.minDate, props.maxDate, props.value, function (error, result) {
    const data = result;
    onData({ data }, null);
  });
};
```

Any idea?

**Comment by thomasKn** [comment]
Many thanks @RevelsGit ! It works like a charm ;)
