### ISSUE TITLE
Wrapped component not re-rendered

### ISSUE THREAD

**Issue by marbemac** [kadirahq/react-komposer#14]
The composer function is re-rendered fine (the console.log('render') below fires). However, the wrapped component (EndpointList) is not re-rendered (there is a console.log in that component that does not fire after the initial render, even when 'render' outputs in the composer function). 

If we wrap onData with a 0 setTimeout, the wrapped component is re-rendered properly.

Anything jump out at you? Thanks!

```js
export const composer = ({context, currentId, cacheUpdate, cacheGet}, onData) => {
  const {Meteor, Collections, LocalState} = context();

  const scope = ['endpoints', 'list', currentId || 'root'],
        scopedCache = cacheGet(scope) || {};

  console.log('render');
  // setTimeout(() => {
  onData(null, {
    cacheUpdateHandler: (operation, path, value) => {
      cacheUpdate(operation, scope, path, value);
    },
  });
  // }, 0);
};

const depsMapper = (context, actions) => ({
  cacheUpdate: actions.cache.update,
  cacheGet: actions.cache.get,
  context: () => context,
});

export default composeAll(
  composeWithTracker(composer),
  useDeps(depsMapper)
)(EndpointList);
```

**Comment by arunoda** [comment]
Hey, do you still have this issue. I'd like to see a sample repo or something similar. I can't get a reason by looking at this.

**Comment by marbemac** [comment]
Sure I'll play around with it tomorrow, and try and create a little reproducible example for ya.

**Comment by marbemac** [comment]
So this turned out to be a flexbox repaint issue in Chrome v48. Yes.. that took me FOREVER to figure out. Chrome 48 introduced all sorts of headaches re flexbox! Closing this :).
