### ISSUE TITLE
Why wrapping the component with a div?

### ISSUE THREAD

**Issue by minfawang** [kadirahq/react-komposer#15]
Notice [here](https://github.com/kadirahq/react-komposer/blob/master/lib/index.js#L56-L61) the container returned wraps the inner component with a `<div />`, which creates inconsistency of the view of the component. I think this wrapping is unnecessary, as depending on the if condition we are only going to show one component at a time. Can we (and I think we should) get rid of the wrapped div?

Thanks!

**Comment by arunoda** [comment]
Yeah. We can get rid of it. Could you work on it and send me a PR?

**Comment by minfawang** [comment]
Cool! Will do.

**Comment by arunoda** [comment]
Awesome.
