### ISSUE TITLE
Better naming (error "Check the render method of `Container(ChildComponent)`")

### ISSUE THREAD

**Issue by zvictor** [kadirahq/react-komposer#17]
# Scenario
I am having a hard time debugging my containers and the way `react-komposer` is naming them is not helping me.

```haskell
Warning:
  React.createElement: type should not be null, undefined, boolean, or number.
    It should be a string (for DOM elements) or a ReactClass (for composite components).
    Check the render method of `Container(ChildComponent)`.
```

# Proposal

Add a `name` or `displayName`  attribute to the composer.
```js
const onPropsChange = (props, onData) => {
  ...
};

onPropsChange.name = 'Clock';
```

**Comment by zvictor** [comment]
I realised that `compose` returns a `React.Component`, which can just be modified and extended.

**Comment by arunoda** [comment]
Yeah! I will close this.
