### ISSUE TITLE
Redux: whole app is re-rendered on every state update

### ISSUE THREAD

**Issue by achtan** [kadirahq/react-komposer#19]
hi, lets assume we have (Mantra) container like this:
`````
export const composer = ({context}, onData) => {
  const {store} = context();

  return store.subscribe(() => {
    const {foo} = store.getState();
    onData(null, {foo});
  })
};

export default composeAll(
  compose(composer),
  useDeps()
)(FooComponent);
````
but on every and any state change my component is re-rendered because of `store.subscribe`.

So for example if I change `bar` value of my state my `FooComponent` will be also re-rendered despite that `foo` value of state is the same as it was...

any idea how to fix this?

**Comment by arunoda** [comment]
Okay. I know the issue.
For that, you need to check for `{foo}` is the same foo with the previous time and then don't call onData.
Fixing this in the app level can be tricky.

So, I suggest to do it on the core level.
Here's the place: https://github.com/kadirahq/react-komposer/blob/master/lib/index.js#L78

You need to check the identity of all the fields in payload with the `previous` time. If the fields are the same. Then don't set the state.

**Comment by achtan** [comment]
I'm not sure what you are suggesting. You want me to write a PR or? (i'm not sure if i'm the right person to do that)

we should implement functionality from PureRenderMixin https://facebook.github.io/react/docs/pure-render-mixin.html because all components should be pure

**Comment by arunoda** [comment]
I  think I'll do it. That's it.

**Comment by arunoda** [comment]
Hey, check the latest version (`v1.3.0`). I fixed this bug there.
See more info: https://github.com/kadirahq/react-komposer#pure-containers

**Comment by achtan** [comment]
thx, ist working!

**Comment by arunoda** [comment]
Cool. Then we can close this.
