### ISSUE TITLE
Option to not unsubscribe subscriptions with composeWithTracker

### ISSUE THREAD

**Issue by markoshust** [kadirahq/react-komposer#21]
Right now, I'm using ReactMeteorData mixin with https://github.com/kadirahq/subs-manager

Caching subscriptions is crucial to my app so everything is always instant.

In this article, you noted that subscriptions are automatically unsubscribed after container unmount:
https://voice.kadira.io/using-meteor-data-and-react-with-meteor-1-3-13cb0935dedb#.oq8bos4u3

Is there (or can there be) an option to not unsubscribe subscriptions on unmount? I believe if there was, I wouldn't need subs-manager anymore?

Cheers,
Mark

**Comment by arunoda** [comment]
@markoshust This is just like ReactMeteorData.(Since it runs a tracker) There is no built in way to do that.
You need to use subs-manager.

**Comment by markoshust** [comment]
Ok no prob -- thanks
