### ISSUE TITLE
Creating layout component

### ISSUE THREAD

**Issue by Mistaken3lf** [kadirahq/react-komposer#24]
How would I create a layout component to hold different components on the page that receive data from komposer. For instance: 

This is the component that receives data from komposer
```
import React from 'react';
import Table from 'material-ui/lib/table/table';
import TableHeaderColumn from 'material-ui/lib/table/table-header-column';
import TableRow from 'material-ui/lib/table/table-row';
import TableHeader from 'material-ui/lib/table/table-header';
import TableRowColumn from 'material-ui/lib/table/table-row-column';
import TableBody from 'material-ui/lib/table/table-body';

const BOMItem = ({bomItems}) => (
  <div>
    <Table>
      <TableHeader>
        <TableRow>
          <TableHeaderColumn>BOM Item #</TableHeaderColumn>
          <TableHeaderColumn>Description</TableHeaderColumn>
        </TableRow>
      </TableHeader>
      <TableBody>
        {bomItems.map(({_id, bomItemNumber, bomDescription}) => (
          <TableRow key={_id}>
            <TableRowColumn>{bomItemNumber}</TableRowColumn>
            <TableRowColumn>{bomDescription}</TableRowColumn>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  </div>
);

export default BOMItem;
```

I would like to use this layout component to put that component inside of

```
import React from 'react';
import BOMItem from './BOMItem.jsx';

const BOMLayout = ({bomItems}) => (
  <div>
    <div className="row">
      <div className="col-sm-12">
        <BOMItem />
      </div>
    </div>
  </div>
);

export default BOMLayout;

```
Im using react-komposer, react-mounter and meteor 1.3 beta 5. Im very new to react so im not real sure how to go about getting the layout component for a BOM inside of the main layout component and display the BOMItem inside the BOMLayout. Do I need to somehow pass props from the BOMLayout to the BOMItem and then loop through it to display all BOMItems in the collection. Any help would be appreciated.

**Comment by arunoda** [comment]
Okay do this.

Create a container for `BOMItem` and let's say it is `BOMItemContainer`.
Then in the layout, import `BOMItemContainer` instead of `BOMItem` and render it.

**Comment by Mistaken3lf** [comment]
I actually have a container for the BOM item and then in the router it renders the BOM item container. My problem though is how do I render the BOM layout inside the main layout and have the BOM item inside the BOM layout with the data from the container since I have to mount the BOM item to get data can I mount the BOM layout and pass data from it to the BOM item?

**Comment by Mistaken3lf** [comment]
Here is the container: 

```
import {composeWithTracker} from 'react-komposer';
import BOMItem from '../../components/BOMItem/BOMItem.jsx';

function composer(props, onData) {
  const handle = Meteor.subscribe('bomItems');
  if(handle.ready()) {
    const bomItems = BOMItems.find().fetch();
    onData(null, {bomItems});
  };
};

export default composeWithTracker(composer)(BOMItem);
```

Then here is the router: 

```
import React from 'react';
import {mount} from 'react-mounter';
import Layout from '../components/Layout/Layout.jsx';
import Home from '../components/Home/Home.jsx';
import BOMItem from '../containers/BOMItem/BOMItemContainer.js';

FlowRouter.route("/", {
  action() {
    mount(Layout, {
        content: (<Home />)
    });
  }
});

FlowRouter.route("/BOMItem", {
  action() {
    mount(Layout, {
        content: (<BOMItem />)
    });
  }
});

```

What I would like to do for the /BOMItem route is instead of rendering the BOMItem directly I would like to render the layout for that page first and then put then put the BOMItem in the BOMLayout and render the <BOMLayout /> instead but im not sure how to get the data into the BOMItem if I mount the BOMLayout.
