### ISSUE TITLE
Subscriptions in Parent Components aren't accessible from Dynamically mounted Children

### ISSUE THREAD

**Issue by TimFletcher** [kadirahq/react-komposer#26]
Not sure if this is a general Meteor thing or with react-komposer.

I have simple a container that subscribes to a collection and passes that data in as props to a component. This works perfectly.

If I dynamically mount a new child component into this component (say, it's a panel in a tabbed interface) then in this child component I'm not able to access any of the subscriptions from the parent. If I try to do something like:

```javascript
render() {
  Collection.Templates.findOne({ _id: this.props.templateId });
}
```

Then I'll always get `undefined`. I can pass the data into the child as props, that works fine, but not access it from MiniMongo. It's as if the subscription doesn't exist within the dynamically mounted child.

**Comment by arunoda** [comment]
It's better to have a sample repo. Cannot say like this.

**Comment by TimFletcher** [comment]
Well, I cloned the Mantra sample repo and couldn't reproduce the problem so it must be an issue in my app.
