### ISSUE TITLE
Meteor - Issue with some integration tests since Tracker is not a dependency

### ISSUE THREAD

**Issue by clayne11** [kadirahq/react-komposer#27]
Since Tracker isn't required by react-komposer, I'm getting into a situation in some of my unit tests where Tracker isn't defined and it is causing exceptions. Either the Tracker portion should be put into an Atmosphere package or you should check if Tracker exists before using it.

**Comment by arunoda** [comment]
Can I have more information on this and a sample app?

**Comment by arunoda** [comment]
@clayne11 I assume, Tracker is there on all apps?

**Comment by clayne11** [comment]
Tracker is available at the app level and in several of the packages but I don't necessarily have Tracker as an explicit dependency in every package.

Mongo collections are automatically reactive in Meteor (using Tracker under the hood), but I don't explicitly depend on Tracker every time I use a Mongo collection.

**Comment by clayne11** [comment]
I just tried this out again and everything seems to be working. I've done a pretty big clean-up in my codebase so I think the issue was actually with my code not yours. Apologies.
