### ISSUE TITLE
It does not refresh the data when visiting a new page

### ISSUE THREAD

**Issue by THPubs** [kadirahq/react-komposer#31]
Im trying to load data based on the url of the page. Unfortunately, it does not refresh the data. Let's say I have two links. I click the first link and the data loads fine. But when I go back and click the second link, it shows the data of the first link. How can I fix this? Please help. Here's my container code :

    import { composeWithTracker } from 'react-komposer';
    import SingleBoxPage from './SingleBoxPage.jsx';

    function composer (props, onData) {
      const boxSlug = FlowRouter.getParam('boxSlug');

      const pageSub = Meteor.subscribe('singleBoxPage', boxSlug);

      if (pageSub.ready()) {
        const pageData = Boxes.findOne();
        const boxId = pageData._id;

        const boxSectionSub = Meteor.subscribe('boxSections', boxId);
        const boxSectionsGallerySub = Meteor.subscribe('boxSectionGallery', boxId);
        const boxSectionGalleryImagesSub =
          Meteor.subscribe('boxSectionGalleryImages');
        const headerImagesSub = Meteor.subscribe('boxPageHeaderImages', boxId);

        if (boxSectionSub.ready() &&
            boxSectionsGallerySub.ready() &&
            boxSectionGalleryImagesSub.ready() &&
            headerImagesSub.ready()
        ) {

          // Get page header
          const headerImage = PageHeaderImages.findOne();
          let headerImageUrl = '';
          if (headerImage) {
            headerImageUrl = PageHeaderImages.findOne().url();
          }

          const boxSectionData = BoxSections.find().fetch();

          onData(null, { pageData, boxSectionData, headerImageUrl });
        }
      }
    }

    export default composeWithTracker(composer)(SingleBoxPage);

**Comment by arunoda** [comment]
I can't find an issue here. need a sample app.

**Comment by THPubs** [comment]
Just fixed the issue! Looks like if we subscribe to a one page's data when visiting that page, it keep those data. So when I visit the second page, there are two pages subscribed! When I call `Boxes.findOne();` I expected to have only one box. But now there are two and the first one gets picked.

Is this normal? Or should it drop the old data when going to a new page like in a normal meteor app (without react) ?

**Comment by arunoda** [comment]
That won't happen normally. But it's possible here because, React component may be not be unmounted yet, when the other component is mounting. 

Is always a good practice to find document you always need.

**Comment by THPubs** [comment]
Oh great thanks! (Sorry for the late reply :-) )
