### ISSUE TITLE
 componentDidMount in komposer ??

### ISSUE THREAD

**Issue by roberto68** [kadirahq/react-komposer#32]
imagine you want to load google maps and you want them to load on init - so after komponent did mount? how to do it in compose function or anything you want to do once when component is loaded

**Comment by lyquocnam** [comment]
same question too...

**Comment by TimFletcher** [comment]
Can't you just use `componentDidMount` in the component that komposer wraps? You don't have to use the stateless functional component form that's used in the examples. If you need any of the other React lifecycle methods then just use `React.createClass` or `MyComponent extends React.Component`.

**Comment by arunoda** [comment]
Yes.  @TimFletcher  is correct. You need to use `componentDidMount` on the React Component. Use a composer to just load the data.

**Comment by roberto68** [comment]
or I can use both komposer for lifecycle and also componentDidMount, right?
