### ISSUE TITLE
Pass props to LoadingComponent

### ISSUE THREAD

**Issue by mikesurowiec** [kadirahq/react-komposer#37]
I'm currently migrating a project to use react-komposer. We have things that aren't displaying properly because props (like className) aren't being applied to the loading component. Is there a downside to passing those props through? Looking at: https://github.com/kadirahq/react-komposer/blob/master/lib/index.js#L74.

**Comment by mikesurowiec** [comment]
I realized we can just call onData immediately (without data) to bypass the loading component, so this is unnecessary.

**Comment by arunoda** [comment]
Exactly.
