### ISSUE TITLE
Using react-komposer with react-native

### ISSUE THREAD

**Issue by superandrew213** [kadirahq/react-komposer#38]
Has anyone gotten this to work? I am trying to use mantra-core with react-native but get the error that mantra core can't load 'react-composer'. Installing react-composer without mantra-core still causes the same issue.

To replicate, create blank react-native app. Install react-composer and import (import {createApp} from 'react-composer';)  it in index.ios.js.

I'm getting the following issue. Already tried the following:

1. The suggested solution on the screenshot.
2. Installing module using npm 2 and 3 and deleting node_modules and installing again.

![screen shot 2016-02-23 at 9 02 39 am](https://cloud.githubusercontent.com/assets/13059204/13235860/439e92e0-da0c-11e5-818b-e301bf8e5891.png)

**Comment by arunoda** [comment]
I'm also seeing it. Will try to fix.

**Comment by superandrew213** [comment]
@arunoda ok thanks. Let me know if you need any help. Would like to use mantra on a react-native project.

**Comment by arunoda** [comment]
Yes. We need some help. If you can find the problem and fix it to work on ReactNative, that's super awesome.

**Comment by smooJitter** [comment]
@superandrew213, what do you suspect?

**Comment by superandrew213** [comment]
@smooJitter not sure. Maybe something to do with babel?

**Comment by yanivnizry** [comment]
+1 for react-native support

**Comment by superandrew213** [comment]
Has anyone made any progress on this?

**Comment by superandrew213** [comment]
@arunoda could it have something to do with the html tags (like <p>Loading...</p>)

**Comment by superandrew213** [comment]
Adding mantra-core and react-composer src manually to project seems to make react-composer available. However now I'm getting this:

![screen shot 2016-03-14 at 3 53 54 pm](https://cloud.githubusercontent.com/assets/13059204/13736249/7d4c0804-e9fe-11e5-840d-45fb2a698d63.png)

**Comment by superandrew213** [comment]
Removing the option in .babelrc of react-display-name module dose remove the error and mantra-core seems to work.

**Comment by yanivnizry** [comment]
@superandrew213 can you explain which option did you removed ?

**Comment by superandrew213** [comment]
@yanivnizry make sure you are using react-display-name v0.0.1. Latest version is using babel 6 and removing the option doesn't work.

react-display-name v0.0.1  has two options. Remove them both.

**Comment by yanivnizry** [comment]
@superandrew213 thank you.
@arunoda can you please fix this issue in the next versions ?

**Comment by arunoda** [comment]
Yeah. We can. 
@superandrew213 send me a PR

**Comment by smooJitter** [comment]
I would love to use Mantra via react-native.  I know you guys are busy but it would be nice to at least have a small list of complication that would need to be addressed. This repo ( spencercarli/react-native-meteor-boilerplate) provides a framework for connecting to meteor from a react-native client via node-ddp.  I also looked at Kadira React Native Demo with GraphQL, which sounds promising but Apollo is still in early stages.  For those considering  Meteor + Mantra + React-Native prototypes, It would be nice to have a little direction regarding Mantra compatible client / server technologies to support GraphQL and routing (e.g., react-native-router-flux, exNavigator, ExperimentalNavigation). Furthermore how would "context" configurations change.

**Comment by superandrew213** [comment]
@arunoda it's just a hack. I manually added both mantra-core and react-komposer source into project root dir and imported the manually added react-komposer in mantra-core. 

After doing that I got the error with react-display-name babel options. So I went into the module and just removed the options. (Note you have to downgrade react-display-name to v0.01 if it is higher. It doesn't work with the new version).

**Comment by arunoda** [comment]
@superandrew213 Hmm. If that's the issue, let's try to remove `react-display-name`. I'll try with it.

**Comment by superandrew213** [comment]
@arunoda adding `"react-native": "./dist/index.js",` to package.json fixes everything. 

Still need to remove `react-display-name` from `react-simple-di`.

Sent you pr's.

**Comment by arunoda** [comment]
That's cool. I'll take this.
May be we can remove that package from react-simple-di.

I'll do a release now and ping you.

**Comment by superandrew213** [comment]
yep removed it already and sent you pr.

**Comment by arunoda** [comment]
FYI: Updated `mantra-core` with updated `react-komposer` and `react-simple-di`.
So, you could simply use `mantra-core` in React native right away.

**Comment by superandrew213** [comment]
hmm I expected that the react p component would cause an error

![screen shot 2016-03-16 at 4 51 17 pm](https://cloud.githubusercontent.com/assets/13059204/13804302/7d46a8a6-eb97-11e5-9a5a-0bb1ebd196ef.png)

**Comment by yanivnizry** [comment]
@superandrew213 what are you using for reactivity instead of Tracker ? did you tried https://github.com/aleclarson/tracker

**Comment by superandrew213** [comment]
Not yet but will check it out. Right now I'm using redux.

**Comment by superandrew213** [comment]
For now you can set your own react-native loading and error components like so: https://github.com/kadirahq/react-komposer#change-the-loading-component

@arunoda maybe we can use `navigator.product === 'ReactNative'` to check. What do you think?

**Comment by arunoda** [comment]
Yeah. We should try to detect that and load appropriate Loading components in RN.
If `navigator.product === 'ReactNative'` works, we should try to use it.

**Comment by superandrew213** [comment]
Yes it works, it was added in react-native v0.17.0.
https://github.com/facebook/react-native/releases/tag/v0.17.0

However to show react-native views and text components we might need to add react-native as a dependency.

**Comment by arunoda** [comment]
Can't we simply get that RN Text component? If not, we should try to add RN as a peer-dependancy.

**Comment by superandrew213** [comment]
I'm not sure whether you can get the Text component only.

What you think about this?
https://github.com/superandrew213/react-komposer/commit/64c51e73d0e1f771d35c0fb1764116735e1b9a02

**Comment by arunoda** [comment]
Closing this since, we already support RN. But, we need to provide loading components manually. That's bit of an issue. We could fix this with #8
