### ISSUE TITLE
Pass props into loading component

### ISSUE THREAD

**Issue by clayne11** [kadirahq/react-komposer#40]
The loading component should receive props so that we can render a loading view that is conditional on the props at this point.

An example is that I would like to render a user's profile photo in the loading component while I am loading other data, however I only have access to that user as a passed in prop.

**Comment by clayne11** [comment]
Please look at this PR as well, it's very small and has a test as well.

**Comment by cellog** [comment]
+1

**Comment by olecrivain** [comment]
+1 !

**Comment by thiagodelgado111** [comment]
Any plans on merging that one into master?

**Comment by newswim** [comment]
I'd really love this feature, what's preventing #47 it from being merged?
