### ISSUE TITLE
[Question] SSR and Cleanup

### ISSUE THREAD

**Issue by sammkj** [kadirahq/react-komposer#43]
> SSR
> 
> In the server, we won't be able to cleanup resources even if you return the cleanup function. That's because, there is no functionality to detect component unmount in the server. So, make sure to handle the cleanup logic by yourself in the server.

I don't quite understand this part. Let's say I'm using Mantra, Flow Router SSR and Redux and I have a container that looks like this:

```
import drawer from '../components/drawer.jsx';
import { compose, composeAll } from 'mantra-core';

export const composer = ({ context }, onData) => {
  const { Store } = context();

  const unsubscribe = Store.subscribe(() => {
    const isDrawerOpen = Store.getState().drawer.DRAWER_IS_OPEN;
    onData(null, { isDrawerOpen });
  });

  const isDrawerOpen = Store.getState().drawer.DRAWER_IS_OPEN;
  onData(null, { isDrawerOpen });

  const cleanUp = () => {
    unsubscribe();
  };

  return cleanUp;
};

export default composeAll(
  compose(composer)
)(Drawer);
```

So, in this case, does that mean that `unsubscribe()` won't get called? should I be worried about this?

**Comment by arunoda** [comment]
Yes it won't run in the server. But that won't be an issue.
For SSR, we need to create a new Context from the scratch. Otherwise, there'll be issues related race conditions. 

I'm working on a way to deal with this.

**Comment by arunoda** [comment]
Let's track this here: https://github.com/kadirahq/mantra/issues/11
