### ISSUE TITLE
Pass context as well as props

### ISSUE THREAD

**Issue by clayne11** [kadirahq/react-komposer#45]
I need access to context as well as props in my compose functions.

I propose we add a third argument to the onPropsChange function, so it would be `fn(props, onData, context)`. This way we aren't making a breaking change to the API.

**Comment by clayne11** [comment]
Can you please take a look at my PR? I think it's reasonable. It won't affect anyone who isn't using context.

**Comment by TimFletcher** [comment]
Isn't `context()` already a attribute of `props`? If you do a `console.log` of the props argument then you should get something like this:

```
actions: function actions()
cdnUrl: "localhost:4000/tm.js"
context: function context()
mode: "development"
```

Where `mode` and `cdnUrl` are props passed to the component in my example.

**Comment by clayne11** [comment]
I'm talking about the React [context](https://facebook.github.io/react/docs/context.html) not the Mantra context and no it's not.

**Comment by TimFletcher** [comment]
Gotcha. I didn't realise you mean the React context.

**Comment by amitava82** [comment]
Any update? I'm trying to use react material-ui which passes stuff down through context and it's not working.
