### ISSUE TITLE
Do we need to clean up the data for Meteor subscription? 

### ISSUE THREAD

**Issue by minfawang** [kadirahq/react-komposer#5]
I just noticed the **Caveats** from the README talking about handling the clean up logic.

I wonder do we need to unsubscribe the data in the case of Meteor subscription (for both client and server)?

**Comment by arunoda** [comment]
No you don't need to do in client. Tracker will take care of it.
In the server, FlowRouter SSR knows how to deal with unsubscriptions.

**Comment by minfawang** [comment]
Thanks for the clarification! Closing it ..

**Comment by ffxsam** [comment]
I came here to post about this very thing.

```
const Time = ({time}) => (<div>Time is: {time}</div>);
const composerFunction = (props, onData) => {
  const handler = Meteor.subscribe('serverTime');
  if(handler.ready()) {
    const {time} = ServerTimeCollection.findOne();
    onData(null, {time});
  } else {
    onData(null, null);
  }
};
 
// Note the use of composeWithTracker 
const Clock = composeWithTracker(composerFunction)(Time);
```

I'm used to template-based subscriptions in Blaze, or subscribing in `getMeteorData` in React. When exactly will a particular subscription stop, with Komposer?

**Comment by arunoda** [comment]
It's just like the getMeteorData, when the component get unmonted.

**Comment by diegolaciar** [comment]
@arunoda ,

So, when the component get unmounted composeWithTracker call   .stop() method for each subscription I made inside the compose function ?

You say I don't need to return a clear function for all the subscriptions?

Thanks,
Diego

From meteor doc:

Stopping Subscriptions

The subscription handle also has another important property, the .stop() method. When you are subscribing, it is very important to ensure that you always call .stop() on the subscription when you are done with it. This ensures that the documents sent by the subscription are cleared from your local Minimongo cache and the server stops doing the work required to service your subscription. If you forget to call stop, you’ll consume unnecessary resources both on the client and the server.

However, if you call Meteor.subscribe() conditionally inside a reactive context (such as an autorun, or getMeteorData in React) or via this.subscribe() in a Blaze component, then Meteor’s reactive system will automatically call this.stop() for you at the appropriate time.
