### ISSUE TITLE
pure: true does not work for nested property

### ISSUE THREAD

**Issue by macrozone** [kadirahq/react-komposer#51]
I have composed this container: 

````
// MapContainer.jsx

function composer({mapId}, onData) {
	let subscriptions = [
		Meteor.subscribe('Map.one', mapId),
		Meteor.subscribe('Zones.forMap', mapId),
	]
  if (_.every(subscriptions, (s) => s.ready())) {
    let map = Maps.findOne(mapId);
    onData(null, {map});
  };
};
export default MapContainer = composeWithTracker(composer, Loader)(MapComponent);
`````

And I call it in a router:

``````
FlowRouter.route("/map/:mapId", {
  name: "Map",
  action({mapId}) {
    mount(MainLayout, {
      content: <MapContainer mapId={mapId}/>
    });
  }
});
````

now, everytime i change a query-param in the url (but keep the mapId in the path), the route is re-run and therefore also the composer.

There is this "purity-check" that should prevent an updated on the component, but it does not. The Problem is this: `_shallowequal2.default(this.state.payload, nextState.payload);` which returns false if the state contains object as values (in this case a map-collection-document).

I am not sure if this is the intended behavior, but it is certainly a big gotcha. Any Idea how to fix this?

**Comment by clayne11** [comment]
It definitely the intended behavior - pure works by performing a shallowEqual. Deep equals can be extremely complex and expensive and thus they are not feasible solutions.

The issue here is actually with Meteor - fetching the same record from Minimongo, even if it hasn't changed, is never the same object, so a triple equals will always fail. This means that tons of views get re-run and re-rendered in Meteor unnecessarily. I wish there was a good solution for this but I don't know of any.

**Comment by arunoda** [comment]
@clayne11 is correct. We only do a shallowEqual. Doing deepEqual is kind a costly for a library like this.
This is not the correct answer, but try using something like immutableJS if the performance really hurts you.

**Comment by macrozone** [comment]
Hi Guys,

thank you for your feedback.

Performance is not costly in my case, the problem is, that the loading-component is showing, because the subscription re-runs. Is it possible to prevent the komposer from re-running when the props it is called with are the same?

**Comment by arunoda** [comment]
You can also set `onData(null, {}) from the every beginning to stop showing the loading container.
