### ISSUE TITLE
Not reacting to changes

### ISSUE THREAD

**Issue by gabriel-dehan** [kadirahq/react-komposer#52]
Hello,

I am pretty new to the mantra architecture and react-komposer but I thought that composeWithTracker was supposed to handle reactive changes from Tracker (i.e, I am a navbar component, I am subscribed to 'user.current' and the users log in, I should have my component re-rendered). Maybe I am mistaking (I would love some clarification), but the commit https://github.com/kadirahq/react-komposer/commit/f1753f277c5f253de139366e041e2391ff3d1295 seems to remove this capability.
What is the correct way to go about it ? Use TrackerReact or getMeteorData ? I am missing something ?

Thanks a lot

**Comment by clayne11** [comment]
The commit you referenced does not remove reactivity. It wraps the `Tracker.autorun` in a `Tracker.nonreactive` so that stopping an outer `Tracker.autorun` does not stop the inner `Tracker.autorun` on the react-komposer container.

This commit is actually a fix to the Tracker reactivity, not taking it away. I would recommend using react-komposer over either of the solutions you suggested. It allows for a much more modular and composable architecture.

**Comment by gabriel-dehan** [comment]
Okay, good to know, thanks ! 

But then why does it seems that my Component is not reactive ? I have this : https://gist.github.com/gabriel-dehan/17cb83fbb6de95d9ebe8

And when I create a new account, login, logout (through the console) nothing happens and the composer function seems not to be called again (but the subscription data should have changed, and `Meteor.userId()` now returns something else).

Is there something I am doing wrong ?

Thanks

**Comment by clayne11** [comment]
You've set up your subscription to use a callback rather than using Tracker reactivity.

Rather than this:

```
Meteor.subscribe('users:current', () => {
	const loggedIn = Meteor.userId() || false;
	const user = Meteor.users.findOne(Meteor.userId());
	onData(null, {loggedIn, user});
});
```

you want to do this:

```
Meteor.subscribe('users:current');
	const loggedIn = Meteor.userId() || false;
	const user = Meteor.users.findOne(Meteor.userId());
	onData(null, {loggedIn, user});
```

I think that should fix your issue.

**Comment by gabriel-dehan** [comment]
It works, thanks ! 

Wondering why 
```javascript
if (Meteor.subscribe('users:current').ready()) {
    const loggedIn = Meteor.userId() || false;
    const user = Meteor.users.findOne(Meteor.userId());
    onData(null, {loggedIn, user});
  }
```
did not work then, it seems to me it's pretty much the same thing except that we are checking if the subscription is ready ?

**Comment by clayne11** [comment]
I believe you have to call onData with something otherwise the function won't complete properly.

```
if (Meteor.subscribe('users:current').ready()) {
    const loggedIn = Meteor.userId() || false;
    const user = Meteor.users.findOne(Meteor.userId());
    onData(null, {loggedIn, user});
 }
```

**Comment by gabriel-dehan** [comment]
That's it :+1:  I tried with an `else` clause and as long as onData is called it seems to be reactive.

Thanks a lot for your help, I am trying to get my head around all those new concepts :)
