### ISSUE TITLE
What am I missing - Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by genyded** [kadirahq/react-komposer#54]
I have the following two files and when I put the <CountryList/> on any page I get an error: `Uncaught TypeError: Cannot read property 'map' of undefined` - any ideas? 

CountryContainer.jsx:

```
import {composeWithTracker} from 'react-komposer'
import CountryList from 'common/client/components/list/CountryList.jsx'
import Countries from 'common/collections/Countries'

function composer(props, onData) {
  if (Meteor.subscribe('countries').ready()) {
    const countries = Countries.find({}).fetch()
    onData(null, {countries})
  };
};

export default composeWithTracker(composer)(CountryList)

```

CountryList.jsx:

```
import React from 'react';

const CountryList = ({countries}) => (
  <div>
    This is the country list: <br/>
    <ul>
      {countries.map((_id, country) => (
        <li key={_id}>
          <h3>{country}</h3>
        </li>
      ))}
    </ul>
  </div>
);

export default CountryList;
```

**Comment by clayne11** [comment]
When your if statement evaluates to false you don't return any data thus countries is null. You cannot map over a null value. If you change your `CountryList` to have a default value it will work:

```
const CountryList = ({countries = []}) => (
  <div>
    This is the country list: <br/>
    <ul>
      {countries.map((_id, country) => (
        <li key={_id}>
          <h3>{country}</h3>
        </li>
      ))}
    </ul>
  </div>
);
```

**Comment by genyded** [comment]
Thanks... that gets past the error, but then the countries never load (or show Loading... like Komposer says they should). The same query works with getMeteorData, so I doubt it's a data issue. Am I missing something else? 

Also the example [here](https://voice.kadira.io/using-meteor-data-and-react-with-meteor-1-3-13cb0935dedb#.v46a4oomy) does not set a default value and I followed that so someone may want to update it,

**Comment by clayne11** [comment]
If you want them to show loading you have call `onData` with no arguments:

```
function composer(props, onData) {
  if (Meteor.subscribe('countries').ready()) {
    const countries = Countries.find({}).fetch()
    onData(null, {countries})
    return;
  };

  onData();
};
```

In terms of the data not loading, my best guess is that something is wrong with your subscription, not `react-komposer`.

**Comment by genyded** [comment]
PK - will keep playing and see if I can figure it out - thanks for the fast responses!

**Comment by genyded** [comment]
Just FYI - in case anyone else runs into it... if you're silly like me and import the LIST (or whatever your component is) and not the CONTAINER... you will not get any errors, but you will not get any data either.

**Comment by saddiqueasad1** [comment]
import React, { Component } from 'react';

import Counter from './conuter';
class Conuters extends Component {
    state = { 
        conuters: [
            { id: 1, value: 4 },
            { id: 2, value: 0 },
            { id: 3, value: 0 },
            { id: 4, value: 0 }
        ]
     }

     handelDelete = (counterid) => {
      const conuters = this.state.conuters.filter(c => c.id !== counterid);
      this.setState({conuters});   
    }

    handelReset = () => {
    // const counters = [...this.state.conuters];
      const counters= this.state.counters.map(c => {
          c.value = 10;
            return c;
        });
       this.setState({ counters });
     }

      handelClick = counter => {
      const counters = [...this.state.conuters];
     const index = counters.indexOf(counter);     
       counters[index].value++;
       this.setState({ counters }); 
    }
   
    render() { 
        return (
            <div>
                <button onClick={this.handelReset()} className="btn btn-primary btn-sm m-2">reset</button>
               {this.state.conuters.map(counter =>
                 <Counter 
                  key={counter.id}
                  onDelete={this.handelDelete}
                  onIncerment={this.handelClick}
                  counter={counter}
                  >
                
                 </Counter>
                 )}
            </div>
         );
    }
}
 
export default Conuters;

**Comment by saddiqueasad1** [comment]
same problem on map

**Comment by jcrommar** [comment]
Thanks, definitely worked!  

const List = ({ Names = []})

**Comment by simranshikha** [comment]
my indexOf not increase data

**Comment by programmer-krish** [comment]
`Uncaught TypeError: Cannot read property 'map' of undefined`
 import React from 'react';
  import { Row, Col } from 'react-bootstrap';
  import WeatherCard from './WeatherCard';

  const WeatherList = ({ weathers =[]}) => (
    <Row>
      {weathers.map(({ dt, temp, weather }, index) =>
        <Col key={index}>
          <WeatherCard
            min={temp.min}
            max={temp.max}
            dt={dt * 1000}
            main={weather[0].main}
            icon={weather[0].icon}
          />
        </Col>
      )}
    </Row>
  );

  export default WeatherList;


import React from 'react';
import './App.css';
import CitySelector from './Component/CitySelector';
import {apiKey, baseUrl} from './config';
import { Container } from 'react-bootstrap';
import useFetch from './hooks/useFetch';
import WeatherList from './Component/WeatherList';


const App = () => {
  const { data, error, inProgress, setUrl } = useFetch();
const getContent = () => {
    if (error) return <h2>Error when fetching: {error}</h2>;
    if (!data && inProgress) return <h2>Loading...</h2>;
    if (!data) return null;
    return <WeatherList weathers ={data.list} />;

    // onData();
  };

return (
      <Container className="App">

       <CitySelector onSelectButtonClick={city => setUrl(`${baseUrl}/data/2.5/forecast/daily?q=${city}&cnt=2&appId=${apiKey}&units=metric`)} />
      {getContent()}

      </Container>
    );

**Comment by Tiruvengadam85** [comment]
Hi All,

Iam also getting similar issue TypeError: Cannot read property 'map' of undefined react,

when I want to destructure an item  array
  return items.map(item => (
      <li>{item}</li>
    ));

`0: {applied_rule_ids: "XXX", base_currency_code: "AED", base_discount_amount: -310, base_grand_total: 300, base_discount_tax_compensation_amount: 14.78}
1: {applied_rule_ids: "YYY", base_currency_code: "AED", base_discount_amount: 0, base_grand_total: 170, base_discount_tax_compensation_amount: 0}
2: {base_currency_code: "AED", base_discount_amount: 0, base_discount_invoiced: 0, base_grand_total: 50, base_discount_tax_compensation_amount: 0}
3: {base_currency_code: "AED", base_discount_amount: 0, base_discount_invoiced: 0, base_grand_total: 100, base_discount_tax_compensation_amount: 0}`

Above is array

**Comment by usama147** [comment]
TypeError: Cannot read property 'map' of undefined
HomeScreen
C:/Users/User/Documents/React_Projects/shoppingwebsite/frontend/src/screens/HomeScreen.js:22
  19 | 
  20 |  return loading? <div>Loading..</div>:
  21 |    error?<div></div>:
> 22 |    <ul className="products">
     | ^  23 |    {products.map(product=>
  24 |        <li key={product._id}>
  25 |         <div className="product">

/* Can someone help me too please?? It'll be much appreciated*/

**Comment by usama147** [comment]
![problem](https://user-images.githubusercontent.com/61545674/87953883-e34e4f80-caab-11ea-8387-8a2fc253d954.png)
can someone please help

**Comment by ntinykumar** [comment]
I am using out of the box SPFX list form modern reach js webpart and it was running well earlier on the sharepoint site online. Suddently it has started showining error. "TypeError: Cannot read property 'map' of undefined". can anyone tell me the fix of this ? Can git hub has updated there online libraries and this issues is causing error due to that. Git hub please fix the issues and get it work again.
