### ISSUE TITLE
Real World Example

### ISSUE THREAD

**Issue by genyded** [kadirahq/react-komposer#58]
Are there any plans to provide a real world example? Clocks are cute, but do not provide any insight in to how to apply something like Komposer to real world scenarios with cross cutting concerns. For example, now you you pass something like the current user to ALL dynamic child components (assuming the children change based on the route)?

The provided examples are way to simplistic.

**Comment by clayne11** [comment]
`react-komposer` wraps a single component. What do you mean by "ALL dynamic child components"?

If you're looking for a way to pass the user down to all your components, you might consider using [context](https://facebook.github.io/react/docs/context.html).

Fetch the user in your `react-komposer` function, then in the component it is wrapping set it up to pass the user down through context.

Your question isn't really in the scope of the `react-komposer` library.

**Comment by arunoda** [comment]
@genyded context is the thing you may need.
You may try this as well: https://github.com/kadirahq/react-simple-di
