### ISSUE TITLE
Cleanup function is being called a lot

### ISSUE THREAD

**Issue by hyperh** [kadirahq/react-komposer#60]
I find that the cleanup function is always being run in my containers, even though the Component in the container hasn't been removed from the screen.

The docs say `It needs to cleanup resources (like subscriptions) when the container is unmounting.` So I assume the cleanup function is only run when the container is unmounting. Which means that the container is being constantly unmounted and re-mounted. Not sure what is going on here.

Code is below.

```js
import {useDeps, composeWithTracker, composeAll} from 'mantra-core';
import TeamInfo from '../components/HeaderMenuItems/TeamInfo.jsx';

const depsMapper = (context, actions) => ({
  context: () => context
});

export const composer = ({context}, onData) => {
  const {Meteor, Collections, FlowRouter} = context();

  const teamId = FlowRouter.getParam('teamId');
  if (teamId) {
    if (Meteor.subscribe('teams.single', {teamId}).ready()) {
      const team = Collections.Teams.findOne(teamId);

      onData(null, {
        teamName: team.name,
        teamInfo: team.info
      });
    }
  }

  return () => console.log('team_info cleanup');
};

export default composeAll(
  composeWithTracker(composer),
  useDeps(depsMapper)
)(TeamInfo);

```

**Comment by arunoda** [comment]
That's because it's running when you are receiving new props.
I assume this is also related to this: https://github.com/kadirahq/react-komposer/issues/2

**Comment by hyperh** [comment]
Does the context changing count as receiving new props? For example, if Collections.Notes (which isn't used in this container) has a changed document, does this container still get the new Collections.Notes prop?

**Comment by arunoda** [comment]
Since context is a function, it won't have an issue. I don't think changing something inside a collection has an issue for this. 

But, when your routes are changing, it's possible to run these again and again. I've some plans to stop this. I'll work on a fix.

**Comment by hyperh** [comment]
So the composer function re-runs whenever my route changes? Which means my Component that the Container wraps receives new props from onData?

**Comment by clayne11** [comment]
Anytime your component receives new props it will run the cleanup function and then resubscribe to the data.

**Comment by arunoda** [comment]
This is by design and we could see some improvements with https://github.com/kadirahq/react-komposer/issues/2
