### ISSUE TITLE
[solved]After upgrading to Meteor 1.3

### ISSUE THREAD

**Issue by smooJitter** [kadirahq/react-komposer#63]
Komposer hangs on loading after upgrading to meteor 1.3.   So far I've tried upgrading to 1.4.1 but that did not solve the problem.  Any suggestions on how can find what's blocking the subscription.

`
import PostList from '../components/postlist.jsx';
import {useDeps, composeWithTracker, composeAll} from 'mantra-core';

export const composer = ({context}, onData) => {
  const {Meteor, Collections} = context();

  if (Meteor.subscribe('posts.list').ready()) {
    const posts = Collections.Posts.find().fetch();
    onData(null, {posts});
  }
};
export default composeAll(
  composeWithTracker(composer),
  useDeps()
)(PostList);

`
The code is from the official mantra demo.

**Comment by arunoda** [comment]
Okay. I think we can close this now.
