### ISSUE TITLE
Meteor client side collection

### ISSUE THREAD

**Issue by nickpolet** [kadirahq/react-komposer#65]
Trying to use this with a client side collection with meteor. Are there any required steps to get this working? I have used react-komposer for server/client collections, but not client only.

**Comment by minfawang** [comment]
`composeWithTracker`  primarily just wraps a `Tracker.autorun` around the function you provided to make it reactive. So it should be no problem using it with a client side collection.

**Comment by arunoda** [comment]
I think this is already answered.
