### ISSUE TITLE
Possible to assign a ref to UI component?

### ISSUE THREAD

**Issue by ndarilek** [kadirahq/react-komposer#67]
Trying to refactor a component to a contained/pure pair. This is a web RTC component, so at some point I need to attach audio/video streams to `<video/>` elements contained in the UI. In order to keep the component pure, this needs to be done in the container logic.

Is there any way to render the UI component with a known, fixed ref? Then I could call this.refs.ui.refs.localVideo or this.refs.ui.refs.remoteVideo to get access to the contained video elements. I recognize this is ugly, but the only other way I can think to do this is to assign ids to the video elements, and that's even uglier. :) Open to any other suggestions on how the container component can access elements in the UI component. I can almost guarantee the UI component will be mounted and visible at the point where the elements need to be accessed, so I'm not concerned about it not being available at time of use.

Thanks.

**Comment by arunoda** [comment]
Hmm. Not sure.

But the container component does not about the UI component and it doesn't store the ref. I sure you can directly do this inside the UI component. Just use container for data fetching.

**Comment by shoetten** [comment]
I have a similar issue. I'm trying to access the public API of an underlying UI component via ref.
But since the ref points to the container component, i cannot access the functions of the UI component.
Is there any way, to access the UI component via a reference, or am i tackling this from the wrong way entirely?

**Comment by minfawang** [comment]
@shoetten This article describes exactly this use case: https://medium.com/@erikras/the-hoc-drill-pattern-a676a3889ced?source=linkShare-9614e68f389f-1465831073

**Comment by clayne11** [comment]
I think we should add the ability to add a ref to the underlying component. I'm going to add a PR.

**Comment by arunoda** [comment]
@clayne11 great. Thanks. I'll get your other PR as well.

**Comment by clayne11** [comment]
PR is done.
