### ISSUE TITLE
Composer functions that depend on prop provided by other composer functions

### ISSUE THREAD

**Issue by dulguun0225** [kadirahq/react-komposer#72]
Is it possible with react-komposer? 

`composerA` does `onData(null,{a});`
`composerB` does `if(a) onData(null,{bs}`

```
composeAll(
  composeWithTracker(composerA),
  composeWithTracker(composerB)
)(Component);
```

Full SO question in detail.
http://stackoverflow.com/questions/36519195/react-komposer-composer-functions-that-depend-on-prop-provided-by-other-compose

**Comment by dulguun0225** [comment]
composeAll composes the functions from right to left. If you depend on a prop from componentA in componentB you need to put componentB above componentA:

```
export const ThisLoadsForever = composeAll(
  composeWithTracker(composerB),
  composeWithTracker(composerA)
)(Component);
```

**Comment by Narzerus** [comment]
This got me confused as well, shouldn't this be running the other way around? I kinda understand WHY it happens, but it is a behavior no one expects and is counter-intuitive

**Comment by dulguun0225** [comment]
Even after figuring out the order, it had some strange behavior that I couldn't remember atm. Then I ended up using single big composer function.

**Comment by sveinburne** [comment]
@dulguun0225 There is a bug with composing `composeWithTracker`'s where props are erased by the lowest composer. Does it echo to your experience ?

**Comment by dulguun0225** [comment]
No. But I think higher order components hide props of inner component.
