### ISSUE TITLE
reverse params to onData()?

### ISSUE THREAD

**Issue by cellog** [kadirahq/react-komposer#73]
Hi,

as a new user for react-komposer, I ran into a snag.  I called onData(props) with no error.  The error message was something about passing in an Error object, which was very confusing.  It took me 45 minutes to realize I needed to pass in null for an error object.

It seems to me, passing an error is much less likely to be as common as passing in props.  Why not reverse the order of parameters, so onData(props) is the default, and onData(props, error) is the way to do that?

**Comment by MasterAM** [comment]
Actually, the convention for node.js callbacks is sending an `error` as the first argument and the data as the second, so this pattern is familiar to many of the developers using node.

Here's a [nice blog post](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/) about it.

**Comment by arunoda** [comment]
closing as already answered.
