### ISSUE TITLE
Install failed with react 15

### ISSUE THREAD

**Issue by pricetula** [kadirahq/react-komposer#75]
Installation failed when i upgraded to these react dependencies :-
"dependencies": {
    "react": "^15.0.0-rc.1",
    "react-dom": "^15.0.0-rc.1"
  }
while installing -> npm install react-komposer I get the error below.

npm WARN peerDependencies The peer dependency react@^0.14.3 || ^15.0.0 included from react-komposer will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/home/user/.nvm/versions/node/v4.2.2/bin/node" "/home/user/.nvm/versions/node/v4.2.2/bin/npm" "install" "react-komposer"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.0.0-rc.1 wants react@^15.0.0-rc.1
npm ERR! peerinvalid Peer react-komposer@1.8.0 wants react@^0.14.3 || ^15.0.0

**Comment by arunoda** [comment]
Hope this is good.
