### ISSUE TITLE
Error :Should provide a child component to build the higher order container.

### ISSUE THREAD

**Issue by ansonla3** [kadirahq/react-komposer#76]
**ListPostsContainer.js
**`import {composeWithTracker} from 'react-komposer';
import { Topics } from '../../lib/collections/Topics.js';
import ListPosts from '../components/post/ListPosts.jsx';

const composer = (props, onData) => {
  const handle = Meteor.subscribe("topics");

  if (handle.ready()) {
    const postsList = Topics.find().fetch();
    onData(null, {postsList});
  }
};

const Container = composeWithTracker(composer)(ListPosts);

export default Container;`

**ListPosts.jsx
**`export const ListPosts = ( { postsList } ) => (
  <div>
    <h1>Testingggg</h1>
  </div>
);`

**routes.js
**
Then, import the ListPostsContainer , then mount to the content

Not sure why I got the error. Please help.

**browser.js?9520:40Uncaught Invariant Violation: Should provide a child component to build the higher order container.
**

**Comment by VenelinPetkov** [comment]
I am facing the same problem.... It is really strangely as I have two containers for one it is working (without props) and for the other (with props) it is not working. Do you have any progress?

**Comment by VenelinPetkov** [comment]
FYI, I simply move the composeWithTracker at the end of the definitions of the componets and it worked... No comments...

**Comment by arunoda** [comment]
Not sure this is still there. Open this with an example repo, if the issue is already there.
