### ISSUE TITLE
Add a way to set the default loading and error components

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-komposer#8]

**Comment by tonyxiao** [comment]
Agreed, also it's not possible to pass a loading element into composeAll right now.

**Comment by TimFletcher** [comment]
This is documented and works just fine for me using

```javascript

import React from 'react';
const MyLoading = () => React.createElement("div", null, "Hmm...");

export default composeAll(
  composeWithTracker(composer, MyLoading),
  useDeps()
)(CampaignPreviewTemplate);
```

**Comment by tonyxiao** [comment]
@TimFletcher yea i later discovered that too. It works fine but I think a better way of writing it would be

```
import React from 'react';
const MyLoading = () => React.createElement("div", null, "Hmm...");

export default composeAll(
  composeWithTracker(composer),
  useDeps()
)(CampaignPreviewTemplate, MyLoading);
```

**Comment by clayne11** [comment]
I actually think it makes sense to have each composer function have it's own loading component since it's possible that you would want to show a different loading screen depending on what data is being fetched.

I have another requirement though that doesn't seem to currently be in scope. I would like to be able to render my loading component using props that are passed into it.

My example is that I would like to render a user's profile photo in the loading component while I am loading other user data, however I only have access to that user as a passed in prop.

**Comment by nmaro** [comment]
+1

**Comment by PolGuixe** [comment]
+1

**Comment by achtan** [comment]
+1
please

**Comment by arunoda** [comment]
Implement this and released with `v1.11.0`.
See docs: https://github.com/kadirahq/react-komposer#change-default-components

**Comment by PolGuixe** [comment]
Where is the best place to define and set this components? 

Inside `client/modules/core/configs` I have created a file called `react-komposer-configs.js`, where I define and set the loading and error component. Then this is imported and called in the `configs` folder `index.js`, which is imported and called from the `index.js` core folder. **However it is NOT working**

I made a gist https://gist.github.com/PolGuixe/42c572704986b79ea3ce2a8f80ad2409 with the code.

**Comment by rafaelcorreiapoli** [comment]
I'm also facing issues with this. I set the default components but I get an error telling me that I "Should provide a loading component in react native"

**Comment by clayne11** [comment]
There's a bug in the current implementation that doesn't allow for setting of default loading and error components in React Native.

https://github.com/kadirahq/react-komposer/blob/master/lib/compose.js#L22

I would open a separate issue for this.

**Comment by arunoda** [comment]
@clayne11 yes. Would love to see a PR as well for that.

**Comment by PolGuixe** [comment]
Is it working for normal react as well? I am having issues.

**Comment by macrozone** [comment]
@PolGuixe: maybe related to this? https://github.com/kadirahq/react-komposer/issues/114

**Comment by PolGuixe** [comment]
@macrozone: most likely it is. Have you found a solution?

**Comment by clayne11** [comment]
A simple PR would fix it. Move the fetching of the loading element into `render`.
