### ISSUE TITLE
Detect state change in composer function

### ISSUE THREAD

**Issue by dulguun0225** [kadirahq/react-komposer#86]
Is it possible to detect state change of a component in composer function?

**Comment by arunoda** [comment]
Could you give us more information on this?

**Comment by dulguun0225** [comment]
As of now we can already detect props change inside a composer function, right? I was wondering if there could be same thing for state, but only read only access to components state.

**Comment by macrozone** [comment]
React-komposer does not detect props-change, maybe there is a misunderstanding.

Additionally, you never have access from "outside" to a component's state, so that also makes little sense to me. Maybe you can explain what you want to achieve with this 👍

**Comment by dulguun0225** [comment]
I wanted to shorten this chain "component -> action -> ReactiveDict -> container" into "component -> container". 

For example if I wanted to set the ordering 

1. component calls action
2. action does the ReactiveDict.set('ordering', 'asc')
3. container reads ReactiveDict.get('ordering')

this could be lot shorter if

1. component does this.setState({ordering : 'asc'})
2. container reads value of that state

**Comment by clayne11** [comment]
I'm really not following. Why do you need `react-komposer` if you're simply calling `setState`? You can just not use `react-komposer` at all. Maybe you'd be better off with a library like [`recompose`](https://github.com/acdlite/recompose)

**Comment by dulguun0225** [comment]
Need it to set parameter to subscription.

**Comment by dulguun0225** [comment]
I guess people don't get it because I'm asking for what doesn't exist in React. Can higher order component read wrapped component's state?

**Comment by macrozone** [comment]
No. You can't read a component's state from outside. And that's a good thing. 

With stateless components you "know" everything about your component anyway, because you pass everything as property

**Comment by dulguun0225** [comment]
I thought if it is just a read access it would not be a bad practice
