### ISSUE TITLE
composeWithTracker should also get a cleanup function. 

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-komposer#9]
We should accept a cleanup function with composeWithTracker too. Just like earlier it only run when unmounting the component.

**Comment by arunoda** [comment]
Fixed with 1dbce80e71f3d47b99bf1630560883aecb116ad9

**Comment by tonyxiao** [comment]
@arunoda I know you definition clarified the reason for this in a separate issue in a different repo. But I can't remember what it is anymore. Could you clarify here again?
