### ISSUE TITLE
State, context, component lifecycle like recompose?

### ISSUE THREAD

**Issue by sammkj** [kadirahq/react-komposer#92]
[`recompose`](https://github.com/acdlite/recompose) already has very simple implementation in place. I wanted to make my components more functional so I extracted a few from the package and modified it to fit `react-komposer`. I will be adding more features if needed

See [here](https://github.com/sammkj/react-komposer-specs). Would you like to add that into `'react-komposer`?

**Comment by clayne11** [comment]
Why wouldn't you just use `recompose`?

**Comment by arunoda** [comment]
Yep. I agree with @clayne11 
Both similar projects, but this one specially to load data.
It's definitely to use both together. We should document that.
